version: '3.8'

services:
  frontend:
    image: node:18
    container_name: swachhaganjam_frontend_container
    build: ./swachhganjam_frontend
    working_dir: /app
    volumes:
      - ./swachhganjam_frontend:/app         # Mount source code
      - dist_data:/app/dist                  # Share dist folder
    command: >
      sh -c "npm install && npm run build"

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - dist_data:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

volumes:
  dist_data:
